username: # Insert your username here
password: # Insert your password here

positions:
- # Data Scientist
# - Another position you want to search for
# - A third position you want to search for

locations:
- Remote
# - A second location you want to search in 

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo
# Note file_key:file_paths contained inside the uploads section should be writted without a dash ('-') 


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

companysize:
- 10,000+ 
- 5,001-10,000
- 1,001-5,000
- 501-1,000  

blacklist:
# - # Company names you want to ignore

blackListTitles:
#- # Add job titles you want to ignore
